sudo: required
dist: trusty
language: node_js
node_js:
  - '8'

branches:
  only:
    - master

before_script:
- dir
- cd ui
- dir
- npm install -g @angular/cli
- npm install

script: 
- dir
- cd ui
- dir
- ng -v
- ng build --prod --base-href "https://antonio25x.github.io/FarmaciaUI/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: ghpages